#!/bin/bash
# decimal -> binary (bytes), see
# http://unix.stackexchange.com/questions/157648/how-to-convert-an-unsigned-decimal-less-than-132-to-4-bytes-binary-in-bash
while perl -e 'print pack "I>", shift' "$(( RANDOM << 16 | RANDOM ))"
do
    :
done
