#!/bin/bash
N=2000000000
SEED=32749
RANDOM=$SEED

cat <<EOF
#==================================================================
# generator bashRANDOM  seed = $SEED
#==================================================================
type: d
count: $N
numbit: 30
EOF

for (( i=0; i<=$N; i++ ))
do
    printf "%10d\n" $(( RANDOM <<15 | RANDOM ))
done
